version: 0.2

env:
  variables:
    DOCKER_IMAGE: devops-laravel-example
    EKS_CLUSTER_NAME: devops-test-cluster
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...   
      - docker build -t $DOCKER_IMAGE:latest -f infrastructure/docker/Dockerfile .
      - export ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_IMAGE"
      - docker tag $DOCKER_IMAGE:latest $ECR_REPO:latest
      - docker tag $DOCKER_IMAGE:latest $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo $ECR_REPO
      - docker push $ECR_REPO:latest
      - docker push $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CodeBuildKubectlRole --role-session-name codebuild-kubectl --duration-seconds 900)
      - echo $(aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CodeBuildKubectlRole --role-session-name codebuild-kubectl --duration-seconds 900)
      - echo "aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CodeBuildKubectlRole --role-session-name codebuild-kubectl --duration-seconds 900"
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - echo $AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - echo $AWS_SECRET_ACCESS_KEY
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - echo $AWS_SESSION_TOKEN
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name devops-test-cluster
      - kubectl --record deployment.apps/laravel-example-app set image deployment.v1.apps/laravel-example-app devops-laravel-example=$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION